/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChestRouteImport } from './routes/chest'
import { Route as HoldRouteImport } from './routes/hold'
import { Route as LoreRouteImport } from './routes/lore'
import { Route as PlayRouteImport } from './routes/play'
import { Route as TokenRouteImport } from './routes/token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChestRoute = ChestRouteImport.update({
  id: '/chest',
  path: '/chest',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldRoute = HoldRouteImport.update({
  id: '/hold',
  path: '/hold',
  getParentRoute: () => rootRouteImport,
} as any)
const LoreRoute = LoreRouteImport.update({
  id: '/lore',
  path: '/lore',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenRoute = TokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chest': typeof ChestRoute
  '/hold': typeof HoldRoute
  '/lore': typeof LoreRoute
  '/play': typeof PlayRoute
  '/token': typeof TokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chest': typeof ChestRoute
  '/hold': typeof HoldRoute
  '/lore': typeof LoreRoute
  '/play': typeof PlayRoute
  '/token': typeof TokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chest': typeof ChestRoute
  '/hold': typeof HoldRoute
  '/lore': typeof LoreRoute
  '/play': typeof PlayRoute
  '/token': typeof TokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chest' | '/hold' | '/lore' | '/play' | '/token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chest' | '/hold' | '/lore' | '/play' | '/token'
  id: '__root__' | '/' | '/chest' | '/hold' | '/lore' | '/play' | '/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChestRoute: typeof ChestRoute
  HoldRoute: typeof HoldRoute
  LoreRoute: typeof LoreRoute
  PlayRoute: typeof PlayRoute
  TokenRoute: typeof TokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chest': {
      id: '/chest'
      path: '/chest'
      fullPath: '/chest'
      preLoaderRoute: typeof ChestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hold': {
      id: '/hold'
      path: '/hold'
      fullPath: '/hold'
      preLoaderRoute: typeof HoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lore': {
      id: '/lore'
      path: '/lore'
      fullPath: '/lore'
      preLoaderRoute: typeof LoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token': {
      id: '/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChestRoute: ChestRoute,
  HoldRoute: HoldRoute,
  LoreRoute: LoreRoute,
  PlayRoute: PlayRoute,
  TokenRoute: TokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
